name: deploy-to-ec2
on: [push,workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'add-known-hosts-in-next-command'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files with rsync
        run: rsync -avP --delete --exclude '.git' --exclude '.github' --exclude 'data' . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/octave-prediction
